version: '3.0'
services:
  autoheal:
    build:
      context: ./
      dockerfile: Dockerfile
    image: stendan7/autoheal:latest
    restart: always
    container_name: autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL
      - AUTOHEAL_INTERVAL
      - AUTOHEAL_START_PERIOD
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT
      - DOCKER_SOCK
      - CURL_TIMEOUT
      - WEBHOOK_URL
      - DING_WEBHOOK_URL
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro